import { RelationshipConfig } from '../types';

export const RELATIONSHIP_CONFIGS: Record<string, RelationshipConfig> = {
  pair: {
    type: 'pair',
    label: '짝꿍',
    labelMasked: '짝꿍',
    description: '같은 공간 행동 시 스테미나 소모 50% 감소',
    merit: '동행 액션 스테미나 소모 -50%',
    demerit: '상대 패널티 발생 시 연대 패널티 절반 부과',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: true,
  },
  rival: {
    type: 'rival',
    label: '라이벌',
    labelMasked: '경쟁자',
    description: '같은 스탯 경쟁 시 성공률 상승',
    merit: '경쟁 액션 성공률 +20%',
    demerit: '상대보다 스탯이 낮아지면 행동 효율 -10%',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: true,
  },
  guard: {
    type: 'guard',
    label: '보호자-피보호자',
    labelMasked: '보호자-피보호자',
    description: '보호자가 피보호자 대신 데미지 수령 가능',
    merit: '피보호자 대신 데미지 대신 받기 (선택적)',
    demerit: '피보호자 위험 상태 시 보호자 스트레스 +5/루프',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: true,
  },
  accomplice: {
    type: 'accomplice',
    label: '공범',
    labelMasked: '협력자',
    description: '불법 행동 성공률 대폭 상승. 반드시 둘이 함께.',
    merit: '반항심 소모 액션 성공률 +30% (동시 실행 필수)',
    demerit: '한 명 발각 시 공범도 자동 연루, 패널티 공유',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: false,
    canTargetBreak: false,
  },
  debt: {
    type: 'debt',
    label: '채무 관계',
    labelMasked: '금전 약정',
    description: '채권자는 매 학기 시작 시 원을 자동 수령',
    merit: '채권자: 매 루프 시작 시 500원 자동 수령',
    demerit: '채무자 파산 시 채권자 유대감 -10, 채무자 스트레스 +15',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: false,
    canTargetBreak: false,
  },
  informant: {
    type: 'informant',
    label: '정보 거래',
    labelMasked: '정보 교환',
    description: '상대방 스탯 수치를 실시간으로 열람 가능',
    merit: '거래 중 상대방 스탯 전체 실시간 열람',
    demerit: '마스터의 배신 미션 우선 대상이 됨',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: true,
  },
  echo: {
    type: 'echo',
    label: '공동 기억',
    labelMasked: '공동 학습',
    description: '단서와 기억을 공유. 한 명의 발견이 상대에게도 복사됨',
    merit: '발견 단서 자동 공유, 기억 포인트 공유',
    demerit: '상대 인지 붕괴(스트레스 100) 시 내 스트레스 +20 즉시',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: true,
  },
  scapegoat: {
    type: 'scapegoat',
    label: '희생양 계약',
    labelMasked: '협력 약정',
    description: '계약자는 투표 면제 1회. 상대(희생양)는 이 계약을 모름.',
    merit: '투표에서 희생양 지목 면제 1회',
    demerit: '희생양은 자신의 득표 수를 볼 수 없음. 계약 사실을 모름.',
    isSecret: true,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: false,
  },
  watcher: {
    type: 'watcher',
    label: '감시자',
    labelMasked: '관찰자',
    description: '피감시자의 앱 접속 시간과 현재 탭을 실시간으로 열람',
    merit: '피감시자의 activeView, lastActive 실시간 열람',
    demerit: '피감시자는 이 관계를 모름. 일정 기간 미보고 시 관계 역전',
    isSecret: true,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: false,
  },
  mirror: {
    type: 'mirror',
    label: '거울',
    labelMasked: '연동 관계',
    description: '매 루프 종료 시 두 캐릭터의 스탯이 평균값으로 수렴',
    merit: '스탯이 높은 쪽이 낮은 쪽을 끌어올림',
    demerit: '스탯이 낮은 쪽이 높은 쪽을 끌어내림. 일방 해제 불가',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: false,
    canTargetBreak: false,
  },
  benefactor: {
    type: 'benefactor',
    label: '은인-수혜자',
    labelMasked: '은혜 관계',
    description: '수혜자는 매 루프 시작 시 은인에게 원 자동 송금',
    merit: '은인: 매 루프 시작 시 200원 자동 수령',
    demerit: '은인 위험 시 수혜자 미도움이면 유대감 -20 자동 차감',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: false,
    canTargetBreak: false,
  },
  paranoia: {
    type: 'paranoia',
    label: '편집증',
    labelMasked: '주의 관찰',
    description: '한 명이 상대방을 일방적으로 의심. 행동 로그 하루 1회 열람.',
    merit: '상대 행동 로그 하루 1회 열람',
    demerit: '의심받는 쪽은 이 관계를 모름. 의심하는 쪽 스트레스 +5/루프',
    isSecret: true,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: false,
  },
  pact: {
    type: 'pact',
    label: '동반 자살 계약',
    labelMasked: '운명 공동체',
    description: '한 명 탈락 시 상대방 주요 스탯 절반으로 감소. 해제 불가.',
    merit: '없음',
    demerit: '한 명 탈락 시 상대방 스탯 즉시 절반. 해제 불가. 마스터만 앎.',
    isSecret: false,
    isMasterOnly: true,
    canInitiatorBreak: false,
    canTargetBreak: false,
  },
  mentor: {
    type: 'mentor',
    label: '선생-학생',
    labelMasked: '튜터링',
    description: '학생이 멘토와 동행 시 성공률 대폭 상승',
    merit: '학생: 멘토 동행 액션 성공률 +25%',
    demerit: '멘토: 스테미나 소모 1.5배. 학생 스탯이 멘토 초과 시 관계 역전',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: true,
  },
  nemesis: {
    type: 'nemesis',
    label: '적대',
    labelMasked: '긴장 관계',
    description: '상대 실패 시 내 반항심 상승. 상대 성공 시 내 스트레스 상승.',
    merit: '상대 실패마다 반항심 +3',
    demerit: '상대 성공마다 스트레스 +5. 같은 공간 행동 효율 양쪽 -15%',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: true,
  },
  trauma_bond: {
    type: 'trauma_bond',
    label: '공유 트라우마',
    labelMasked: '공동 경험',
    description: '스트레스 연동. 한 명의 극도의 스트레스가 상대에게 전염.',
    merit: '고스트레스 상황에서 서로 위로 액션 효율 2배',
    demerit: '상대 스트레스 80+ 시 내 스트레스 +10 자동. 해제에 마스터 승인 필요',
    isSecret: false,
    isMasterOnly: false,
    canInitiatorBreak: false,
    canTargetBreak: false,
  },
  broker: {
    type: 'broker',
    label: '거래 중개인',
    labelMasked: '거래 보증인',
    description: '중개인을 통한 블랙마켓 거래 수수료 면제',
    merit: '거래 수수료 면제',
    demerit: '중개인은 거래 내역 전부 열람 가능. 상대는 이를 모름.',
    isSecret: true,
    isMasterOnly: false,
    canInitiatorBreak: true,
    canTargetBreak: false,
  },
  curse: {
    type: 'curse',
    label: '저주',
    labelMasked: '저주',
    description: '마스터 전용. 양측 모두 이 관계를 모름.',
    merit: '저주 건 쪽: 대상 특정 액션 시 내 스탯 자동 상승',
    demerit: '저주 건 쪽이 먼저 탈락하면 대상 전체 스탯 일시 절반',
    isSecret: false,
    isMasterOnly: true,
    canInitiatorBreak: false,
    canTargetBreak: false,
  },
};
